from dxfwrite import DXFEngine as dxf

drawing = dxf.drawing(name='layertest.dxf')
#drawing.add_layer('CIRCLE2')
#drawing.add(dxf.circle((10), (10,5), layer='CIRCLE2'))
#drawing.add_layer('CIRCLE')
#drawing.add(dxf.circle((2), (5, 10), layer='CIRCLE'))
drawing.add_layer('RECT')
drawing.add(dxf.rectangle((5, 5) , 6, 6, bgcolor=8, layer='RECT'))
drawing.add_layer('POLY')
polyline= dxf.polyline(linetype='LINE',color=4,layer='POLY')
polyline.add_vertices( [(7,9.5),(6,10), (10,10), (10,6), (6,6),(6,10)])

#polyline.add_vertices( [(5,7.5),(4,8), (8,8), (8,4), (4,4),(4,8)])
#polyline.add_vertices( [(6.5,10), (7,9.5)])
polyline.close(status=True)
polyline.add_vertices( [(5.5,10.5), (10.5,10.5), (10.5,5.5), (5.5,5.5)])
drawing.add(polyline)
drawing.add(dxf.line((7, 9),(6,9.5), color=4))
drawing.add_layer('CIRCLE')
drawing.add(dxf.circle((0.1), (6.5,9.5), layer='CIRCLE'))
drawing.add(dxf.circle((0.1), (9.5,9.5), layer='CIRCLE'))
drawing.add(dxf.circle((0.1), (6.5,6.5), layer='CIRCLE'))
drawing.add(dxf.circle((0.1), (9.5,6.5), layer='CIRCLE'))
drawing.add_layer('TEXTLAYER', color=9)
drawing.add(dxf.text('Layers', (4.9, 6), height=0.5, rotation=90, layer='TEXTLAYER'))
#drawing.add(dxf.dimstyles(4,5))
drawing.save()
